In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
import ipyparallel as ipp
%matplotlib inline

# Tarea 1.

### Ejercicios

Determinar si un numero de la forma $2^n -1$, donde $n$ es un entero, es primo o no. Los primos que tienen esta forma se llaman primos de Mersenne.

* Escribir una funcion que determine si el numero dado por $2^n -1$ es primo (usar la funcion anterior) 

 * Seleccionar los primos de Mersenne de entre los primeros 5000 numeros enteros (nota: el resultado es {2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203, 2281, 3217, 4253, 4423}

* Estimar el tiempo que su computadora tarda en encontrar los primero 5000 primos de Mersenne

In [11]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
numeros = [PrimeQ(2**n-1) for n in range(20)]
numeros

[False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [13]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
numeros = [PrimeQ(2**n-1) for n in range(30)]
numeros

[False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [14]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
numeros = [PrimeQ(2**n-1) for n in range(40)]
numeros

[False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [12]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
numeros = [PrimeQ(2**n-1) for n in range(50)]
numeros

[False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [1]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
%timeit -n1 -r1 [PrimeQ(2**n-1) for n in range(20)]

1 loop, best of 1: 601 µs per loop


In [2]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
%timeit -n1 -r1 [PrimeQ(2**n-1) for n in range(30)]

1 loop, best of 1: 2.27 ms per loop


In [3]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
%timeit -n1 -r1 [PrimeQ(2**n-1) for n in range(40)]

1 loop, best of 1: 80.6 ms per loop


In [1]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
%timeit -n1 -r1 [PrimeQ(2**n-1) for n in range(50)]

1 loop, best of 1: 2.79 s per loop


### El kernel se ditiene durante la ejecución de la función con 1000 números, por lo que con 5000 no sería posible realizar el ejercicio. 

In [ ]:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
numeros = [PrimeQ(2**n-1) for n in range(1000)]
numeros

In [4]:
rango = 20
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
r = [PrimeQ(2**n-1) for n in range(rango)]
for x in range(rango):
    if r[x] == True:
        print x

2
3
5
7
13
17
19
31


In [5]:
rango = 30
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
r = [PrimeQ(2**n-1) for n in range(rango)]
for x in range(rango):
    if r[x] == True:
        print x

2
3
5
7
13
17
19


In [1]:
rango = 40
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
r = [PrimeQ(2**n-1) for n in range(rango)]
for x in range(rango):
    if r[x] == True:
        print x

2
3
5
7
13
17
19
31


In [2]:
rango = 50
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
r = [PrimeQ(2**n-1) for n in range(rango)]
for x in range(rango):
    if r[x] == True:
        print x

2
3
5
7
13
17
19
31


### El kernel se ditiene durante la ejecución de la función con 75 números, por lo que con 5000 no sería posible realizar el ejercicio. 

In [ ]:
rango = 75
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
r = [PrimeQ(2**n-1) for n in range(rango)]
for x in range(rango):
    if r[x] == True:
        print x

### La arquitectura de IPython cuenta con cuatro componentes:
 1. El motor. Es la extensión del kernel para IPython, percibe las solicitudes a través de la red. 
 2. El Hub. Realiza seguimiento de las conexiones del motor. Facilita las consultas del estado del clúster y optimiza la información. 
 3. Los programadores. Todas las acciones que pueden ser ejecutadas por el motor pasan por este componente. 
 4. El controlador. 

Una de las principales desventajas de IPython es la seguridad, ya que no existe cifrado en las conexiones que realiza. La única opción que se tiene disponible es a través de un túnel SSH. 

El controlador cuenta con dos archivos JSON 
ipcontroller-engine.json
ipcontroller-client.json

In [9]:
import ipyparallel as ipp
c = ipp.Client()
dview = c[:]
c.ids

[0, 1, 2, 3, 4, 5, 6, 7]

In [10]:
def multi(a,b):
    return a*b
dview.map_sync(multi, [0,1,3,5],[2,4,6,8])

[0, 4, 18, 40]

In [11]:
rango = 1000
PrimeQ = lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1
m = dview.map_sync(PrimeQ, range(rango))

In [12]:
def getNumero(ra):
    for x in range(1,ra):
        if m[x] == True:
            print(x)

In [13]:
getNumero(rango)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997


## Clase 17 de mayo de 2017

In [ ]:
PrimeQ = lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1


In [17]:
n = 13
r = -1 + 2**n
r

8191

In [17]:
import ipyparallel as ipp

c = ipp.Client()
dview = c[:]
c.ids
    

[0, 1, 2, 3]

In [18]:
#Aplicar una función a todos los motores
dview.apply_sync(lambda: "Hola clase de MCA")

['Hola clase de MCA',
 'Hola clase de MCA',
 'Hola clase de MCA',
 'Hola clase de MCA']

In [19]:
#Aplicar una función en un rago de motores
#apply distribuye la función en todos los motores (a todos les pida que hagan la tarea)
c[0:3].apply_sync(lambda: "Hola clase de MCA")

['Hola clase de MCA', 'Hola clase de MCA', 'Hola clase de MCA']

In [20]:
#map divide la tarea en los motores para generar un solo resultado
c[:].map_sync(lambda x,y,z : x+y+z, range(10), range(10), range(10))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [21]:
import numpy as np
x = 2**13
range(int(x**0.5)+1)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90]

In [22]:
import numpy as np
x = 2**13
np.arange(int(x**0.5)+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90])

In [23]:
x = 2**13
for i in np.arange(int(x**0.5)+1):
    print x % i

0
0
0
2
0
2
2
2
0
2
2
8
8
2
2
2
0
15
2
3
12
2
8
4
8
17
2
11
16
14
2
8
0
8
32
2
20
15
22
2
32
33
2
22
8
2
4
14
32
9
42
32
28
30
38
52
16
41
14
50
32
18
8
2
0
2
8
18
32
50
2
27
56
16
52
17
60
30
2
55
32
11
74
58
44
32
22
14
8
4
2


/Users/luis/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  app.launch_new_instance()


In [24]:
%%timeit -n1 -r1
x = 2**25
for i in np.arange(int(x**0.5)+1):
    print x % i

/Users/luis/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:259: RuntimeWarning: divide by zero encountered in long_scalars


0
0
0
2
0
2
2
2
0
2
2
10
8
2
2
2
0
2
2
14
12
2
10
8
8
7
2
20
16
11
2
1
0
32
2
2
20
20
14
2
32
32
2
27
32
2
8
4
32
16
32
2
28
26
20
32
16
14
40
11
32
40
32
2
0
2
32
28
36
8
2
45
56
55
20
32
52
65
2
51
32
20
32
22
44
2
70
11
32
8
2
2
8
32
4
52
32
95
16
65
32
10
2
19
80
2
26
88
20
90
32
20
16
99
14
77
40
2
70
2
32
43
40
32
32
57
2
16
0
113
2
92
32
128
28
47
104
118
8
110
72
98
116
54
128
127
128
65
20
79
32
118
128
2
142
32
80
78
130
26
32
100
20
67
32
32
22
124
128
158
2
128
156
44
98
107
32
11
8
166
92
109
2
101
8
57
32
87
4
128
52
125
128
31
192
2
16
13
164
47
32
95
10
156
104
32
122
146
80
109
2
157
132
116
88
27
128
156
90
128
32
2
20
68
128
182
212
200
128
207
192
65
40
102
2
192
188
209
2
27
32
2
164
20
40
212
32
223
32
188
182
250
128
54
16
2
0
255
242
205
132
11
92
103
32
132
128
8
28
179
182
25
240
2
118
32
8
37
110
218
72
222
98
254
116
242
54
114
128
87
272
95
128
72
212
247
168
263
228
54
32
156
118
212
128
162
2
253
296
122
32
20
80
206
78
2
288
299
26
98
192
302
100
223
20


# <font color='red'> Tarea : Ejecutar el ejercicio de la celda anterior con un límite de 25 número solicitados. Gráficar los resultados</font>

In [25]:
# El [2:] indica que se toma a partir del segundo elemento
# Hasta este punto no se ha optimizado la parte crítica del programa
funPrimos = lambda x : all (x % i != 0 for i in np.arange(int(x**0.5)+1)[2:]) and x>1

In [49]:
def funPrimosQ(x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:])

In [50]:
funPrimosQ(2**7)

False

In [51]:
c[:].apply_sync(funPrimosQ, 2**7)

[False, False, False, False]

In [65]:
dview = c[:]

In [66]:
%%timeit -n1 -r1
dview.map_sync(funPrimosQ, 2**np.arange(25))

1 loop, best of 1: 15.6 ms per loop


In [67]:
%%timeit -n1 -r1
x = 2**25
for i in np.arange(25)[2:]:
    x % i

1 loop, best of 1: 28.8 µs per loop


In [68]:
all?

In [69]:
np.all(np.array([x % i for i in np.arange(int(x**0.5)+1)[2:]]))

False

In [70]:
def funPrimosQB(x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(int(x**0.5)+1)[2:]]))

In [78]:
%%timeit -n1 -r1 
dview.map_sync(funPrimosQB, 2**np.arange(25))

1 loop, best of 1: 19 ms per loop


In [85]:
%%timeit -n1 -r1 
np.arange(24)

1 loop, best of 1: 14.1 µs per loop


In [92]:
%%timeit -n1 -r1 
np.mod(np.arange(24),12)

1 loop, best of 1: 23.1 µs per loop


In [91]:
%%timeit -n1 -r1 
np.array([hora % 12 for hora in np.arange(24)])

1 loop, best of 1: 43.9 µs per loop


In [94]:
for med in np.arange(12,20):
    print np.mod(np.arange(24), med)

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]


# <font color='red'> Tarea : Remplazar el for de la función de la celda anterior con np</font>

In [95]:
def funPrimosQC(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x, lista)
    return np.all(residuos)

In [99]:
%%timeit -n1 -r1
dview.map_sync(funPrimosQB, 2**np.arange(10))

1 loop, best of 1: 29.1 ms per loop


In [100]:
%%timeit -n1 -r1
dview.map_sync(funPrimosQC, 2**np.arange(10))

1 loop, best of 1: 30.1 ms per loop


# <font color='red'> Tarea : Realizar la gráfica de comparación de tiempo con la funcion funPrimosC</font>